const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const repoRoot = path.resolve(__dirname, '..', '..');
const outPath = path.resolve(__dirname, '..', 'src', 'app', 'version.generated.ts');

function run(cmd, opts = {}) {
  try {
    return execSync(cmd, { encoding: 'utf8', cwd: repoRoot, ...opts }).trim();
  } catch {
    return null;
  }
}

const hash = run('git rev-parse HEAD');
const shortHash = run('git rev-parse --short HEAD');
const date = run('git log -1 --format=%ci HEAD');

const content = `// Generated by scripts/git-version.js – do not edit manually.
export const BUILD_GIT_HASH = ${hash ? `'${hash}'` : 'null'};
export const BUILD_GIT_SHORT = ${shortHash ? `'${shortHash}'` : 'null'};
export const BUILD_DATE = ${date ? `'${date}'` : 'null'};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content, 'utf8');
